var strings = {
	"card_attack": "Attack",
	"card_defuse": "Defuse",
	"card_exploding": "Detonating Cat!",
	"card_favour": "Favour",
	"card_nope": "Nope!",
	"card_random1": "BEANS Cat",
	"card_random2": "random card 2",
	"card_random3": "random card 3",
	"card_random4": "random card 4",
	"card_random5": "random card 5",
	"card_see3": "See the Future (x3)",
	"card_shuffle": "Shuffle",
	"card_skip": "Skip",
	"username_exists": "That username has already been taken. Please try and be more original.",
	"already_connecting": "There is already an active connection. Please reload the page if this problem persists.",
	"one_word": "Your name should be one word.",
	"lobby_one_word": "Lobby names can only be one word.",
	"illegal_move": "Sorry, but the server has disconnected you for moving improperly. This is either a bug or you are trying to cheat.",
	"message_spectating": "You are currently spectating; to join, type <b>/join</b>.",
	"message_spectating_started": "You are spectating and can join once this round has finished.",
	"message_playing": "Type <b>/start</b> to start the game, or <b>/leave</b> to spectate.",
	"bcast_starting": "<span style='color:yellow'>The game is starting!</span>"
};
