var strings = {
	"card_attack": "Attack",
	"card_defuse": "Defuse",
	"card_exploding": "Detonating Cat!",
	"card_favour": "Favour",
	"card_nope": "Nope!",
	"card_random1": "BEANS Cat",
	"card_random2": "CHUFFing Cat",
	"card_random3": "Fridge Cat",
	"card_random4": "Tacky Yack Cat",
	"card_random5": "Bin Guitar Cat",
	"card_see3": "See the Future (x3)",
	"card_shuffle": "Shuffle",
	"card_skip": "Skip",
	"username_exists": "That username has already been taken. Please try and be more original.",
	"already_connecting": "There is already an active connection. Please reload the page if this problem persists.",
	"one_word": "Your name should be one word.",
	"lobby_one_word": "Lobby names can only be one word.",
	"illegal_move": "Sorry, but the server has disconnected you for moving improperly. This is either a bug or you are trying to cheat.",
	"message_spectating": "You are currently spectating; to join, type <b>/join</b>.",
	"message_spectating_started": "You are spectating and can join once this round has finished.",
	"message_spectating_exploded": "You are out for this round.",
	"message_playing": "Type <b>/start</b> to start the game, or <b>/leave</b> to spectate.",
	"bcast_starting": "<span style='color:yellow'>The game is starting!</span>",
	"bcast_new_game": "<span style='color:yellow'>A new game has started.</span>",
	"bcast_no_nope": "Nope! There is nothing to Nope!",
	"bcast_favour_cancel": "The favour was cancelled.",
	"bcast_min_players": "There must be at least 2 players in a game.",
	"bcast_max_players": "There cannot be more than 6 players in a game.",
	"bcast_high_players": "<span style='color:orange'>You are playing with 6 players - the game will still work, but be aware that this is more than intended!</span>",
	"must_defuse": "<span style='color:purple'>You must defuse the Detonating Cat.</span>",
	"question_defuse_pos": "Where should the Detonating Cat be placed in the deck? (0 = on top)",
	"question_favour_who": "Who do you want to ask for a favour?",
	"question_random_who": "Who would you like to ask for a random card?",
	"question_steal_who": "Who would you like to steal a card from?",
	"question_steal_what": "Which card would you like to steal?",
	"conn_closed": "The connection to the server was lost.",
	"bad_version": "The game server is running a different version of the game. If this problem persists, please try hard-reloading the page by pressing Ctrl+F5 or clearing your browser cache.",
	"title_normal": "Detonating Cats",
	"title_alert": "* YOUR TURN! * (Detonating Cats)"
};

var cards = [
	"attack",
	"defuse",
	"exploding",
	"favour",
	"nope",
	"random1",
	"random2",
	"random3",
	"random4",
	"random5",
	"see3",
	"shuffle",
	"skip"
];
